### ISSUE TITLE
Please add collaborators

### ISSUE THREAD

**Issue by sandlerr** [princemaple/hash_schema#8]
👋  @princemaple could you please add me to rubygems for this? It's been serving its purpose without any interference for a very long time, we only just now needed to make a change :D

**Comment by princemaple** [comment]
Sure, I'll do it when I get home this evening, hope it's OK.

**Comment by princemaple** [comment]
@sandlerr I've added rsandler@zendesk.com :)

**Comment by sandlerr** [comment]
Thank you :+1:
